/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChildLight {
    }
    interface ImgBase64Preview {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "initialSrc": string;
    }
    interface ImgMfeBridge {
    }
    interface ImgMfeSafe {
    }
    interface ImgReproLight {
    }
    interface ImgReproShadow {
    }
    interface ImgWecomDocument {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "src": string;
    }
    interface ImgWecomHostBridge {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "src": string;
    }
    interface ImgWeixinBridge {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParentShadow {
    }
}
declare global {
    interface HTMLChildLightElement extends Components.ChildLight, HTMLStencilElement {
    }
    var HTMLChildLightElement: {
        prototype: HTMLChildLightElement;
        new (): HTMLChildLightElement;
    };
    interface HTMLImgBase64PreviewElement extends Components.ImgBase64Preview, HTMLStencilElement {
    }
    var HTMLImgBase64PreviewElement: {
        prototype: HTMLImgBase64PreviewElement;
        new (): HTMLImgBase64PreviewElement;
    };
    interface HTMLImgMfeBridgeElement extends Components.ImgMfeBridge, HTMLStencilElement {
    }
    var HTMLImgMfeBridgeElement: {
        prototype: HTMLImgMfeBridgeElement;
        new (): HTMLImgMfeBridgeElement;
    };
    interface HTMLImgMfeSafeElement extends Components.ImgMfeSafe, HTMLStencilElement {
    }
    var HTMLImgMfeSafeElement: {
        prototype: HTMLImgMfeSafeElement;
        new (): HTMLImgMfeSafeElement;
    };
    interface HTMLImgReproLightElement extends Components.ImgReproLight, HTMLStencilElement {
    }
    var HTMLImgReproLightElement: {
        prototype: HTMLImgReproLightElement;
        new (): HTMLImgReproLightElement;
    };
    interface HTMLImgReproShadowElement extends Components.ImgReproShadow, HTMLStencilElement {
    }
    var HTMLImgReproShadowElement: {
        prototype: HTMLImgReproShadowElement;
        new (): HTMLImgReproShadowElement;
    };
    interface HTMLImgWecomDocumentElement extends Components.ImgWecomDocument, HTMLStencilElement {
    }
    var HTMLImgWecomDocumentElement: {
        prototype: HTMLImgWecomDocumentElement;
        new (): HTMLImgWecomDocumentElement;
    };
    interface HTMLImgWecomHostBridgeElement extends Components.ImgWecomHostBridge, HTMLStencilElement {
    }
    var HTMLImgWecomHostBridgeElement: {
        prototype: HTMLImgWecomHostBridgeElement;
        new (): HTMLImgWecomHostBridgeElement;
    };
    interface HTMLImgWeixinBridgeElement extends Components.ImgWeixinBridge, HTMLStencilElement {
    }
    var HTMLImgWeixinBridgeElement: {
        prototype: HTMLImgWeixinBridgeElement;
        new (): HTMLImgWeixinBridgeElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParentShadowElement extends Components.ParentShadow, HTMLStencilElement {
    }
    var HTMLParentShadowElement: {
        prototype: HTMLParentShadowElement;
        new (): HTMLParentShadowElement;
    };
    interface HTMLElementTagNameMap {
        "child-light": HTMLChildLightElement;
        "img-base64-preview": HTMLImgBase64PreviewElement;
        "img-mfe-bridge": HTMLImgMfeBridgeElement;
        "img-mfe-safe": HTMLImgMfeSafeElement;
        "img-repro-light": HTMLImgReproLightElement;
        "img-repro-shadow": HTMLImgReproShadowElement;
        "img-wecom-document": HTMLImgWecomDocumentElement;
        "img-wecom-host-bridge": HTMLImgWecomHostBridgeElement;
        "img-weixin-bridge": HTMLImgWeixinBridgeElement;
        "my-component": HTMLMyComponentElement;
        "parent-shadow": HTMLParentShadowElement;
    }
}
declare namespace LocalJSX {
    interface ChildLight {
    }
    interface ImgBase64Preview {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "initialSrc"?: string;
    }
    interface ImgMfeBridge {
    }
    interface ImgMfeSafe {
    }
    interface ImgReproLight {
    }
    interface ImgReproShadow {
    }
    interface ImgWecomDocument {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "src"?: string;
    }
    interface ImgWecomHostBridge {
        /**
          * @default 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
         */
        "src"?: string;
    }
    interface ImgWeixinBridge {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParentShadow {
    }

    interface ImgBase64PreviewAttributes {
        "initialSrc": string;
    }
    interface ImgWecomDocumentAttributes {
        "src": string;
    }
    interface ImgWecomHostBridgeAttributes {
        "src": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "child-light": ChildLight;
        "img-base64-preview": Omit<ImgBase64Preview, keyof ImgBase64PreviewAttributes> & { [K in keyof ImgBase64Preview & keyof ImgBase64PreviewAttributes]?: ImgBase64Preview[K] } & { [K in keyof ImgBase64Preview & keyof ImgBase64PreviewAttributes as `attr:${K}`]?: ImgBase64PreviewAttributes[K] } & { [K in keyof ImgBase64Preview & keyof ImgBase64PreviewAttributes as `prop:${K}`]?: ImgBase64Preview[K] };
        "img-mfe-bridge": ImgMfeBridge;
        "img-mfe-safe": ImgMfeSafe;
        "img-repro-light": ImgReproLight;
        "img-repro-shadow": ImgReproShadow;
        "img-wecom-document": Omit<ImgWecomDocument, keyof ImgWecomDocumentAttributes> & { [K in keyof ImgWecomDocument & keyof ImgWecomDocumentAttributes]?: ImgWecomDocument[K] } & { [K in keyof ImgWecomDocument & keyof ImgWecomDocumentAttributes as `attr:${K}`]?: ImgWecomDocumentAttributes[K] } & { [K in keyof ImgWecomDocument & keyof ImgWecomDocumentAttributes as `prop:${K}`]?: ImgWecomDocument[K] };
        "img-wecom-host-bridge": Omit<ImgWecomHostBridge, keyof ImgWecomHostBridgeAttributes> & { [K in keyof ImgWecomHostBridge & keyof ImgWecomHostBridgeAttributes]?: ImgWecomHostBridge[K] } & { [K in keyof ImgWecomHostBridge & keyof ImgWecomHostBridgeAttributes as `attr:${K}`]?: ImgWecomHostBridgeAttributes[K] } & { [K in keyof ImgWecomHostBridge & keyof ImgWecomHostBridgeAttributes as `prop:${K}`]?: ImgWecomHostBridge[K] };
        "img-weixin-bridge": ImgWeixinBridge;
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "parent-shadow": ParentShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "child-light": LocalJSX.IntrinsicElements["child-light"] & JSXBase.HTMLAttributes<HTMLChildLightElement>;
            "img-base64-preview": LocalJSX.IntrinsicElements["img-base64-preview"] & JSXBase.HTMLAttributes<HTMLImgBase64PreviewElement>;
            "img-mfe-bridge": LocalJSX.IntrinsicElements["img-mfe-bridge"] & JSXBase.HTMLAttributes<HTMLImgMfeBridgeElement>;
            "img-mfe-safe": LocalJSX.IntrinsicElements["img-mfe-safe"] & JSXBase.HTMLAttributes<HTMLImgMfeSafeElement>;
            "img-repro-light": LocalJSX.IntrinsicElements["img-repro-light"] & JSXBase.HTMLAttributes<HTMLImgReproLightElement>;
            "img-repro-shadow": LocalJSX.IntrinsicElements["img-repro-shadow"] & JSXBase.HTMLAttributes<HTMLImgReproShadowElement>;
            "img-wecom-document": LocalJSX.IntrinsicElements["img-wecom-document"] & JSXBase.HTMLAttributes<HTMLImgWecomDocumentElement>;
            "img-wecom-host-bridge": LocalJSX.IntrinsicElements["img-wecom-host-bridge"] & JSXBase.HTMLAttributes<HTMLImgWecomHostBridgeElement>;
            "img-weixin-bridge": LocalJSX.IntrinsicElements["img-weixin-bridge"] & JSXBase.HTMLAttributes<HTMLImgWeixinBridgeElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "parent-shadow": LocalJSX.IntrinsicElements["parent-shadow"] & JSXBase.HTMLAttributes<HTMLParentShadowElement>;
        }
    }
}
